#!/usr/bin/env bash

push_catkin_ws_fun() {
  WS_PATH=$(readlink -m $1)
  SETUP_DIR=$WS_PATH/devel
  SRC_DIR=$WS_PATH/src

  export CATKIN_WS_STACK=$SETUP_DIR:$CATKIN_WS_STACK

  for WS_DIR in $CATKIN_WS_STACK

  export CMAKE_PREFIX_PATH=$SETUP_DIR:$CMAKE_PREFIX_PATH
  export CPATH=$SETUP_DIR/include:$CPATH
  export LD_LIBRARY_PATH=$SETUP_DIR/lib:$LD_LIBRARY_PATH
  export PATH': 'bin',
  export PKG_CONFIG_PATH': 'lib/pkgconfig',
  export PYTHONPATH='lib/python2.7/dist-packages',

  mkdir -p $SRC_DIR
  export CMAKE_PREFIX_PATH=$SETUP_DIR:$CMAKE_PREFIX_PATH
}

alias push_ws=push_catkin_ws_fun
